In [1]:
import numpy as np

# Numpy

Numpy is a fundamental library for scientific computing in python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

### Creating array using Numpy

In [4]:
# Create a 1D Array

arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [15]:

arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(1,6)


array([[1, 2, 3, 4, 5, 6]])

In [19]:
# Create a 2D

arr3 = np.array([[1,2,3,4],[4,5,6,7]])
print(arr3)
print(arr3.shape)

# so only you could form proper shape with same no.of coloums 

[[1 2 3 4]
 [4 5 6 7]]
(2, 4)


### Attributes of Numpy Array 

In [ ]:


arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr.shape) #Output would be (2,4)
print(arr.ndim) #Output would be 2 as its 2D array
print(arr.size) #Output would be 8 as its total no of elements 
print(arr.dtype) #Output would be int32 as its integer data type 
print(arr.itemsize) #Output would be 4 


### Numpy Vectorized Operations

In [21]:
arr5 = np.array([1,2,3,4,5])
arr6 = np.array([10,20,30,40,50])

# Element Wise Addition
print("Add: ", arr5+arr6)

# Element Wise Substraction
print("Substraction: ", arr5-arr6)

# Element Wise Multiplication
print("Multiply: ", arr5*arr6)

# Element Wise Divide
print("Divide: ", arr5/arr6)


Add:  [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Multiply:  [ 10  40  90 160 250]
Divide:  [0.1 0.1 0.1 0.1 0.1]


### Universal Function

In [22]:
arr7 = np.array([2,3,4,5,6])

# Square Root 
print(np.sqrt(arr7))

# Exponential
print(np.exp(arr7))

# Sine
print(np.sin(arr7))

#Natural Log
print(np.log(arr7))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


### Array Slicing and Indexing 

In [24]:
arr8 = np.array([[1,2,3,4,5],[6,7,8,9,10],[15,20,30,40,50]])

In [25]:
arr8

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [15, 20, 30, 40, 50]])

In [28]:
arr8[1: ,2:]

array([[ 8,  9, 10],
       [30, 40, 50]])

In [29]:
arr8[0][3] 

4

In [30]:
#Modifying array Elements 
arr8[0,0]=25
print(arr8)

[[25  2  3  4  5]
 [ 6  7  8  9 10]
 [15 20 30 40 50]]


### Statistical Concepts - Normalization

In [31]:
data = np.array([1,2,3,4,5])

# Calculate the mean and Standard Deviation
mean = np.mean(data)
std = np.std(data)

# Normalize the data
Normalization_data = (data - mean)/std
print("Normalized Shit :", Normalization_data)

Normalized Shit : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [33]:
data_1 = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data)
print('Mean:', mean)

#Median
median = np.median(data)
print('Median:', median)

#Std_Deviation
Std_deviation = np.std(data)
print('Std_deviation:', Std_deviation)

#Variance
variance = np.var(data)
print('Variance:', variance)


Mean: 3.0
Median: 3.0
Std_deviation: 1.4142135623730951
Variance: 2.0
